# SPDX-FileCopyrightText: 2022 Red Hat, Inc. <sd-mt-sre@redhat.com>
#
# SPDX-License-Identifier: Apache-2.0

version: 2
updates:
- package-ecosystem: gomod
  directory: /
  schedule:
    interval: daily
  labels:
  - kind/deps
  commit-message:
    prefix: fix
    include: scope
- package-ecosystem: gomod
  directory: /tools
  schedule:
    interval: daily
  labels:
  - kind/deps
  commit-message:
    prefix: fix
    include: scope
