---
run:
  build-tags:
    - codeanalysis
linters:
  enable-all: true
  disable:
  # Deprecated
  - golint
  - interfacer
  - maligned
  - scopelint
  # Only meant to be applied selectively.
  - exhaustivestruct
  # Promotes use of trivially shortened statements rather than
  # lower complexity functions.
  - funlen
  # Standard import ordering is fine for now.
  - gci
  # Globals still in use for singleton-esque objects.
  - gochecknoglobals
  # False reports.
  - ifshort
  - nilerr
  # Interface returns are currently used to wrap chained methods
  # methods from the 'ocm-sdk'.
  - ireturn
  # Does not support map[string]testcase style subtests.
  - paralleltest
  # Ineffective for foreign schemas
  - tagliatelle
  # Tests cannot be blackboxed.
  - testpackage
  # Annoying
  - varnamelen
  # Errors are propagated back to commands.
  - wrapcheck
