# SPDX-FileCopyrightText: 2022 Red Hat, Inc. <sd-mt-sre@redhat.com>
#
# SPDX-License-Identifier: Apache-2.0

---
version: "2"
run:
  build-tags:
    - codeanalysis
linters:
  enable-all: true
  disable:
  # not neccessary right now
  - depguard
  # Only meant to be applied selectively.
  - exhaustruct
  # Promotes use of trivially shortened statements rather than
  # lower complexity functions.
  - funlen
  # Globals still in use for singleton-esque objects.
  - gochecknoglobals
  # False reports.
  - nilerr
  # Interface returns are currently used to wrap chained methods
  # methods from the 'ocm-sdk'.
  - ireturn
  # Does not support map[string]testcase style subtests.
  - paralleltest
  # Ineffective for foreign schemas
  - tagliatelle
  # Tests cannot be blackboxed.
  - testpackage
  # Annoying
  - varnamelen
  # Errors are propagated back to commands.
  - wrapcheck
