# SPDX-FileCopyrightText: 2022 Red Hat, Inc. <sd-mt-sre@redhat.com>
#
# SPDX-License-Identifier: Apache-2.0

version: 2
project_name: ocm-addons
before:
  hooks:
  - make check
builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  main: ./cmd/ocm-addons
  binary: ocm-addons
  ldflags:
  - -s -w
  - -X 'github.com/mt-sre/ocm-addons/internal/meta.version={{.Version}}'
  - -X 'github.com/mt-sre/ocm-addons/internal/meta.commit={{.Commit}}'
  - -X 'github.com/mt-sre/ocm-addons/internal/meta.date={{.Date}}'
  - -X 'github.com/mt-sre/ocm-addons/internal/meta.builtBy=goreleaser'
  hooks:
    post:
    - env:
      - BIN_PATH={{ .Path }}
      cmd: make license-check
archives:
- format_overrides:
  - goos: windows
    format: zip
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  use: github
  groups:
  - title: Breaking
    regexp: "^.*(fix|feat)[(\\w)]*!:+.*$"
    order: 0
  - title: Changes
    regexp: "^.*feat[(\\w)]*:+.*$"
    order: 10
  - title: Bugfixes
    regexp: "^.*fix[(\\w)]*:+.*$"
    order: 20
  - title: Trivial
    order: 999
  filters:
    exclude:
    - Merge pull request
    - '^docs:'
    - '^test:'
