# SPDX-FileCopyrightText: 2024 Red Hat, Inc. <sd-mt-sre@redhat.com>
#
# SPDX-License-Identifier: Apache-2.0

[tools]
go = "1.21"
pre-commit = "2.17.0"
golangci-lint = "latest"
ginkgo = "2.13"
goreleaser = "latest"

[env]
DEPENDENCY_DIR = "{{config_root}}/.cache/dependencies"

[tasks.build]
run = "go build -o {{config_root}}/bin/ocm-addons {{config_root}}/cmd/ocm-addons"

[tasks.install]
run = "go install {{config_root}}/cmd/ocm-addons"

[tasks.lint]
run = "golangci-lint run -v"

[tasks."hooks:enable"]
run = """
    pre-commit install \
    --hook-type pre-commit \
    --hook-type pre-push
    """

[tasks."hooks:run-all-files"]
run = "pre-commit run --all-files"

[tasks."hooks:run-changed"]
run = """
    pre-commit run \
    --show-diff-on-failure \
    --from-ref origin/main \
    --to-ref HEAD
    """

[tasks."check:license"]
run = """
    {{config_root}}/.cache/dependencies/bin/lichen \
    -c {{config_root}}/.lichen.yaml \
    {{config_root}}/bin/ocm-addons
    """
depends = [
    "install-lichen"
]

[tasks.install-lichen]
run = "go install github.com/uw-labs/lichen"
dir = "{{config_root}}/tools"
env.GOBIN = "{{config_root}}/.cache/dependencies/bin"

[tasks."check:tidy"]
depends = [
    "check:tidy-deps",
    "check:tidy-tools",
]

[tasks."check:deps-tidy"]
run = "go mod tidy"

[tasks."check:tools-tidy"]
run = "go mod tidy"
dir = "{{config_root}}/tools"

[tasks."check:verify"]
run = "go mod verify"

[tasks."test:units"]
run = "go test -race -v ./cmd/... ./internal/..."

[tasks."test:integration"]
run = """
    ginkgo \
    -r --randomize-all --randomize-suites \
    --fail-on-pending --keep-going --race \
    --trace -v integration
    """
depends = [
    "install-ocm-cli",
]

[tasks.install-ocm-cli]
run = "go install github.com/openshift-online/ocm-cli/cmd/ocm"
dir = "{{config_root}}/tools"
env.GOBIN = "{{config_root}}/.cache/dependencies/bin"

[tasks.release]
run = "goreleaser release"
depends = [
    "release:clean"
]

[tasks."release:clean"]
run = "rm -rf {{config_root}}/dist"
